<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <Target Condition="'$(CI)'!='TRUE'" AfterTargets="Build" Name="Output">
        <Copy SourceFiles="$(TargetPath)" DestinationFiles="$(GORILLATAG_PATH)/BepInEx/patchers/ConfigurationManager.Patcher.dll" />
    </Target>

    <!-- Dependencies -->
    <ItemGroup Condition="'$(CI)'=='TRUE'">
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2" PrivateAssets="all" />
        <PackageReference Publicize="true" Include="gorillatag" Version="1.0.*"/>
    </ItemGroup>

    <ItemGroup Condition="'$(CI)'!='TRUE'">
        <Reference Include="BepInEx">
            <HintPath>$(GORILLATAG_PATH)\BepInEx\core\BepInEx.dll</HintPath>
        </Reference>
        <Reference Include="HarmonyLib">
            <HintPath>$(GORILLATAG_PATH)\BepInEx\core\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="Mono.Cecil">
            <HintPath>$(GORILLATAG_PATH)\BepInEx\core\Mono.Cecil.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
